[repository]
name = "hyprsplitrow"
authors = ["reversesh3ll"]

[hyprsplitrow]
description = "A Hyprland layout plugin with horizontal or vertical primary/secondary monitor regions."
authors = ["reversesh3ll"]
output = "hyprsplitrow.so"
build = [
    "make clean",
    "make",
]
